### ISSUE TITLE
zmakebas FN problem

### ISSUE THREAD

**Issue by plirof** [zxplay/zxcoder#8]
This is not zxplay fault:
I just like to point that there is a bug in zmakebas with the FN.
eg
```
10 DEF FN a(b)=2*b
20 PRINT FN a(2)
```

will fail in line 20 because the FN conversion is flawed.  
It is a known bug and it was supposed to be resolved but I haven't found the correct version.

**Comment by stever** [comment]
@plirof I've applied the latest v2.1b version from [here](https://zgedneil.nfshost.com/zmakebas.html). There's another version I found [here](https://github.com/chris-y/zmakebas) which produces the same error for your test code above. If you find a better version, please let me know.

**Comment by stever** [comment]
@plirof I've replaced `zmakebas` with `bas2tap` on the zxplay.org home page. This page is really a demo, with more options available when you log in and use the Project menu.

The project menu now contains the option to use either zmakebas or bas2tap.

**Comment by plirof** [comment]
Ok. The only online option I haven't tried is this : [](https://zx.remysharp.com/bas/) . FN works but I haven't tested anything complex

**Comment by plirof** [comment]
I tried the zxplay.org not logged in. Bas2tap has many issues. It can't compile correct even simple programs. Better return the initial page as it was before.

Also, I am using the page from many different and sometimes public devices so I can't log in very easy.
Thanks :)

**Comment by stever** [comment]
Done. Restored zmakebas on front page.
